version: "3.9"

services:
  # Create service with RabbitMQ.
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672 # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    restart: always
    networks:
      - dev-network

  convwriter:
      container_name: convwriter
      ports:
        - 9091:9091
      build:
        context: .
        dockerfile: Dockerfile-convwriter
      environment:
        WRITER_METRICS_HTTP_PORT: 9091
        AMPQ_SERVER_URL: amqp://guest:guest@message-broker:5672/
        AMPQ_CONVERSION_QUEUE: ConversionQueue
      restart: always
      networks:
        - dev-network
      depends_on:
          - message-broker

networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge
